### ISSUE TITLE
MySQL Anbindung nach Update defekt

### ISSUE THREAD

**Issue by procker89** [Schrolli91/BOSWatch#464]
nach dem Update läuft die Datenbank nun nicht mehr, scheinbar weil sie eben nur utf8 nicht utf8mb4 als charset hat (nicht einstellbar) - die Fehlermeldung ist folgende:               

23.07.2020 20:45:30 - MySQL           [DEBUG   ] cannot connect to MySQL
Traceback (most recent call last):
  File "/opt/boswatch/plugins/MySQL/MySQL.py", line 94, in run
    connection = mysql.connector.connect(host = globalVars.config.get("MySQL","dbserver"), port = globalVars.config.get("MySQL","dbport"), user = globalVars.config$
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/__init__.py", line 44, in Connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 107, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 341, in connect
    self.config(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/connection.py", line 220, in config
    collation)[0]
  File "/usr/local/lib/python2.7/dist-packages/mysql/connector/constants.py", line 742, in get_charset_info
    raise ProgrammingError("Character set '%s' unknown." % (charset))
ProgrammingError: Character set 'utf8mb8' unknown.

Vor dem Update lief alles einwandfrei - also Datenbank selbst fehlerfrei.

- **BOSWatch Version 2.5
- **mySQL Plugin Solo aktiviert**

Würde mich über Hilfe sehr freuen. Vielen lieben Dank schon mal. Grüße procker89

**Comment by lgremme** [comment]
Du hast einen falschen Zeichensatz:
```
ProgrammingError: Character set 'utf8mb8' unknown.
```
Mir sind nur utf8 und utf8mb4 bekannt.

**Comment by procker89** [comment]
geändert - allerdings immer noch keine Verbindung.

**Comment by lgremme** [comment]
Falls du vorher bereits den MySQL-Connector installiert hattest, ist die Version wahrscheinlich veraltet:
https://github.com/Schrolli91/BOSWatch/issues/445
Falls du auf utf8mb4 umstellt, solltest du den entsprechenden Zeichensatz verwenden.
