### ISSUE TITLE
Telegram Plugin startet nicht - Python Verision?

### ISSUE THREAD

**Issue by Leitner1** [Schrolli91/BOSWatch#488]
Hallo zusammen,

ich bekomme das Telegram Plugin nicht zum laufen. Sonst ist kein Plugin aktiviert.
SW Version: 2.5.1, Branch:	master

Fehlermeldung:
```
13.10.2020 19:48:28 - pluginLoader    [ERROR   ] error loading plugin: Telegram
13.10.2020 19:48:28 - pluginLoader    [DEBUG   ] error loading plugin: Telegram
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/Telegram/Telegram.py", line 14, in <module>
    import telegram
  File "/usr/local/lib/python2.7/dist-packages/telegram/__init__.py", line 21, in <module>
    from .base import TelegramObject
  File "/usr/local/lib/python2.7/dist-packages/telegram/base.py", line 42
    _id_attrs: Tuple[Any, ...] = ()
             ^
SyntaxError: invalid syntax
```

Wie ich hier gefunden habe, benötigt der Python-Telegram-Bot min Python 3.6
https://stackoverflow.com/questions/64316706/python-telegram-bot-syntax-error-for-the-line-id-attrs-tupleany

Ich habe in der "~/.bashrc" einen alias angelegt "alias python='/usr/bin/python3.7'".
Wenn ich die Version mit "python --version" abfrage kommt "Python 3.7.3" zurück.

Der Python-Telegram-Bot ist für beide Versionen installiert:
/usr/local/lib/python2.7/dist-packages/telegram
und
/usr/local/lib/python3.7/dist-packages/telegram

Ich habe leider keinen näheren Kenntnisse über Python und meine Linux Kenntnisse sind auch nur rudimentär.

Hardware ist ein RPI 1B mit dem Image: 2020-08-20-raspios-buster-armhf-lite

Jemand eine Idee? Sonst setze ich einfach alles nochmals auf....

Danke und viele Grüße
Leitner

**Comment by Leitner1** [comment]
hat sich erledigt...
ich habe alles deinstalliert, python zurück auf Version 2.7.16 gestellt und mit "sudo pip install python-telegram-bot==11.0.0" installiert. So wie hier: https://github.com/Schrolli91/BOSWatch/issues/469#issuecomment-678979340
Sorry ich war zu doof die Suche richtig zu verwendet!
