### ISSUE TITLE
Telegram-Plugin bringt Fehler beim Start

### ISSUE THREAD

**Issue by webstr4711** [Schrolli91/BOSWatch#490]
Hallo,
gemacht habe ich:
pip install python-telegram-bot  (erfolgreich)

BTTokenAPIkey und BOTChatIDAPIKey in config.ini gesetzt

es kommt dieser Fehler

------------------
`
16.11.2020 00:55:28 - pluginLoader    [ERROR   ] cannot load plugin: Telegram
16.11.2020 00:55:28 - pluginLoader    [DEBUG   ] cannot load plugin: Telegram
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/Telegram/Telegram.py", line 14, in <module>
    import telegram
  File "/usr/local/lib/python2.7/dist-packages/telegram/__init__.py", line 21, in <module>
    from .base import TelegramObject
  File "/usr/local/lib/python2.7/dist-packages/telegram/base.py", line 42
    _id_attrs: Tuple[Any, ...] = ()
             ^
SyntaxError: invalid syntax
16.11.2020 00:55:28 - pluginLoader    [ERROR   ] error loading plugin: Telegram
16.11.2020 00:55:28 - pluginLoader    [DEBUG   ] error loading plugin: Telegram
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/Telegram/Telegram.py", line 14, in <module>
    import telegram
  File "/usr/local/lib/python2.7/dist-packages/telegram/__init__.py", line 21, in <module>
    from .base import TelegramObject
  File "/usr/local/lib/python2.7/dist-packages/telegram/base.py", line 42
    _id_attrs: Tuple[Any, ...] = ()
             ^
SyntaxError: invalid syntax
16.11.2020 00:55:28 - boswatch        [DEBUG   ] starting rtl_fm`
-----------------------

Vielen Dank für Eure Hilfe.

**Comment by webstr4711** [comment]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

# uname -a
Linux host2 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux

**Comment by kermit112** [comment]
Schau mal da: https://github.com/Schrolli91/BOSWatch/issues/488
Damit läuft es gerade bei mir, zumindest auf den ersten Blick...
