### ISSUE TITLE
IO Plugin Fehler beim Aufrufen der 

### ISSUE THREAD

**Issue by PasidoPG** [Schrolli91/BOSWatch#499]
Bei Fragen und Problemen zu BOSWatch oder Plugins bitte unten gennante Informationen angeben:

- **BOSWatch Version + Branch** 
 

 SW Version:	2.5.1
master
Build Date:	28.04.2020
Python Vers:	2.7.16 (default, Oct 10 2019, 22:02:15) 

- **genutzte Plugins**

- **Fehlerbeschreibung**

- **Logfile (Auszug)**

- **ggf. Config File (Auszug)**
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 95
    th = threading.Thread(target = trigger)
     ^
IndentationError: expected an indented block
06.01.2021 22:41:55 - pluginLoader    [ERROR   ] error loading plugin: gpiocontrol
06.01.2021 22:41:55 - pluginLoader    [DEBUG   ] error loading plugin: gpiocontrol
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/gpiocontrol/gpiocontrol.py", line 95
    th = threading.Thread(target = trigger)
     ^

**Comment by PasidoPG** [comment]
Hallo zusammen,
habe auf einem Raspi 3 (kpl. neu aufgesetzt) Bosmon instaliert und das IO Plugin aktiviert. Sobald ich Bosmon starte bekomme ich den Fehler - pluginLoader    [ERROR   ] cannot load plugin: gpiocontrol
                       - pluginLoader    [ERROR   ] error loading plugin: gpiocontrol


kann mir hier jemand helfen ?

Danke
