### ISSUE TITLE
Debian 11 Bullseye QT4-Problem

### ISSUE THREAD

**Issue by u918244** [Schrolli91/BOSWatch#524]
Moin,

ich wollte mir eine Testinstanz aufsetzen auf einem Raspberry Pi 1 Mod. B. Dazu wollte ich als Grundlage einmal DietPi ausprobieren. Die Installation von DietPi lief problemlos mit der Bullseye Version, die aktuell zur Verfügung steht.
Leider klappt damit die Installation von BOSWatch nicht. Bis zum Installationsabbruch gibt es zwei Dinge, die nicht funktionieren:
+ Installation von Python
+ Installation von QT4
Bei Python habe ich gelesen, ist jetzt nur noch Python3 in Debian 11 enthalten, das sich aber mit dem im Installscript enthaltenen Befehl nicht installieren lässt. Zur Kompatibilität kann ich nichts sagen, da ich mich mit Python nicht auskenne. QT4 ist wohl in Debian 11 gar nicht mehr enthalten, ob BOSWatch mit QT5 läuft, weißich nicht.
Gibt es außer der Nutzung von älteren Debian-Versionen eine Möglichkeit, BOSWatch auch auf einem aktuellen System einzusetzen?
Dies ist mein erster Post hier, daher bitte nicht gleich in der Luft zerreißen, wenn ich ungenügende Angaben gemacht habe oder mich unüblich ausgedrückt haben sollte. Vielleicht kann mir ja jemand weiterhelfen - würde mich freuen.

Danke und Gruß,
u918244

**Comment by flothi** [comment]
Das Hochziehen auf neue Betriebssysteme ist zugunsten der Entwicklung von Version 3 ausgeblieben. Allerdings weiß ich gerade nicht, wie es um boswatch3 bestellt ist.

Wenn es nicht eilt, schaue ich im Laufe der nächsten Tage mal

**Comment by u918244** [comment]
Aha, das ist natürlich verständlich. Ich habe auch mal versucht, boswatch3 zu installieren. Auch das Installscript bricht mit einer Fehlermeldung bezüglich QT4 ab. Lass Dir ruhig Zeit. Ich habe mittlerweile noch ein Buster-Image von DeitPi gefunden. Das wird dann für meine Testinstanz herhalten... DietPi ist aus meiner Sicht für solche speziellen Anwendungen eine sehr gut geeignete Basis.

**Comment by flothi** [comment]
Ich muss mal gucken, wozu QT überhaupt benötigt wird. Ich glaube nämlich nur für den Build von rtl-fm bzw multimon-ng. Boswatch selber müsste ohne auskommen

**Comment by Schrolli91** [comment]
> Ich glaube nämlich nur für den Build von rtl-fm bzw multimon-ng. Boswatch selber müsste ohne auskommen

Ja das ist so korrekt...

**Comment by letmoc** [comment]
Hi, habe einen Pi neu installieren müssen (SD-Karte defekt)

Raspberry Pi OS with desktop and recommended software
Release date: October 30th 2021
Kernel version: 5.10

Das Installations-Script steigt bei mir auch mit einem Python Fehler aus.
Gibt es einen workaround damit die Installation auf einem aktuellem Betriebssystem funktioniert?

**Comment by Rauchtaucher** [comment]
Moin,

ich stehe nun auch vor der Herausforderung, dass die Neuinstallation an qt4 scheitert. Habt ihr einen Tipp für mich, wie ich das umgehen könnte?

**Comment by letmoc** [comment]
Hi, habe mir das Installations- Script angepasst. Nun funktioniert die Installation auch auf aktuellen Systemen.
Nach der Installation noch das BosWatch.py  Python im Bereich Multimon-ng angepasst und um „-C DE“ erweitert, damit auch die deutschen Sonderzeichen richtig ausgewertet werden können.
Jetzt funktioniert wieder alles

es sind viele Anpassungen in dem Script nötig. Unter anderem kannst du nur qt5 sowie python3 verwenden. Die SDR Treiber und Multimon-ng mussten angepasst werden

**Comment by Rauchtaucher** [comment]
Danke, ich habe nun ebenfalls Anpassungen vorgenommen, sodass die Installation geklappt hat.

Ich bin jedoch bei python 2.7. geblieben, komplett auf v3 umzustellen habe ich auf die Schnelle nicht geschafft.

**Comment by u918244** [comment]
@letmoc , @jaytee34 : Habt Ihr die Änderungen hier abgelegt? Lasst uns doch bitte teilhaben, damit nicht jeder User das Rad neu erfinden muss. Dafür wäre ich sehr dankbar. Ich bin zur temporären Lösung des Problems auf eine alte OS Version gegangen. Das ist jedoch nicht meine favorisierte Lösung.
Merci

**Comment by modus15** [comment]
Hallo, ich würde das Thema gerne wieder aufgreifen. Ich versuche nun unter verschiedenen Umgebungen BosWatch zu installieren. Bei den neuen Images bricht die Installation direkt nach "Git and another Stuff" ab. Phyton Problem
Nun gehe ich in den Images immer weiter zurück, bin bei einem Raspbian von Ende 2017, wo auch Boswatch sehr aktiv war.
Dort läuft der Punkt zwei der Installation schon deutlich weiter, bricht aber mit Exitcode 100 ab, im log dann zu sehen das es u.a. wie hier um QT4 geht, aber auch so viele "http" Adressen nicht gefunden werden.
Gibt es irgendwo eine aktuelle Installationsroutine oder hat gar jemand ein komplettes Image mit Boswatch am laufen, was er mir zur Verfügung stellen kann? Ich verzweifel langsam :(
danke im Vorraus

**Comment by Reissdorf84** [comment]
Hallo Zusammen!
Würde gerne ein neues System aufsetzen, mit dem aktuellen OS auf Raspberry bricht die Installation auch bei mir immer ab. Dann habe ich eine altes OS aus Dezember 20 installiert und auch da bricht die Installation bei Punkt zwei ab. Er läuft zwar wesentlich länger als mit dem aktuellen Betriebssystem aber halt nicht durch. In der install.sh habe ich auch testweise das qt4 durch qt5 ersetzt. Auch ohne Erfolg.
Weiter reichen meine Linuxkenntnisse nicht.
@letmoc und @jaytee34 könnt ihr sagen was ihr noch angepasst habt oder es sogar im git bereitstellen?
Gruß und danke

**Comment by Schrolli91** [comment]
Also falls hier jemand ein angepasstes Install Script per PR bereitstellen mag - gerne.
Nur ich komme selbst leider im Moment nicht dazu, das zu fixen.

**Comment by Rauchtaucher** [comment]
Moin, da "meine" install.sh nicht mehr existierte, habe ich die Anpassungen nochmals vorgenommen und getestet. Bei mir läuft es mit den Anpassungen, ich bin mir aber sicher, dass das Fehlerhandling verbesserungswürdig ist.  Dennoch habe ich einen pull-request gestellt. 

@Reissdorf84: Du kannst es ja mal bei dir testen.

@Schrolli91 Im Nachgang ist mir aufgefallen, dass es wahrscheinlich besser wäre, die install.sh für bullseye und Folgende unter einem anderen Namen zu führen. Da ich github Newbie bin, kannst du da noch eingreifen?

Grüße

**Comment by Schrolli91** [comment]
@jaytee34 hab das bullseye skript in ein eigenes file gepackt.
Merge ich sobald ich im PR Rückmeldungen habe, ob alles funktioniert,.

**Comment by Reissdorf84** [comment]
Installation ist problemlos durchgelaufen. Vielen Dank dafür schon mal.
Werde mich an die Konfiguration geben und dann testen.

**Comment by Skipper1990** [comment]
Mahlzeit,
habe auch mal mein glück probiert. 
Bullseye und Python 3.8.4 und bei mir kommt folgender fehler.

OK:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
OK:2 http://archive.raspberrypi.org/debian bullseye InRelease
Paketlisten werden gelesen…
Paketlisten werden gelesen…
Abhängigkeitsbaum wird aufgebaut…
Statusinformationen werden eingelesen…
Paket python-pip ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.
Doch die folgenden Pakete ersetzen es:
  python3-pip

E: Paket qt4-qmake kann nicht gefunden werden.
E: Paket qt4-default kann nicht gefunden werden.
E: Für Paket »python-pip« existiert kein Installationskandidat.
Action: download on stuff failed.
Exitcode: 100

**Comment by Skipper1990** [comment]
Mahlzeit, 
habe mich auch mal probiert.
OS Bullseye und Python 3.8.4

Installation lief sauber durch, nur beim starte kommt ein fehler.

Info: Telegram mit sudo pip install python-telegram-bot installiert

Folgender fehler beim start von Boswatch

28.05.2022 13:02:11 - pluginLoader    [DEBUG   ] load plugin: Telegram
28.05.2022 13:02:11 - pluginLoader    [ERROR   ] cannot load plugin: Telegram
28.05.2022 13:02:11 - pluginLoader    [DEBUG   ] cannot load plugin: Telegram
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/Telegram/Telegram.py", line 14, in <module>
    import telegram
ImportError: No module named telegram
28.05.2022 13:02:11 - pluginLoader    [ERROR   ] error loading plugin: Telegram
28.05.2022 13:02:11 - pluginLoader    [DEBUG   ] error loading plugin: Telegram
Traceback (most recent call last):
  File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
    plugin = loadPlugin(i)
  File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
    return imp.load_module(plugin["name"], *plugin["info"])
  File "/opt/boswatch/plugins/Telegram/Telegram.py", line 14, in <module>
    import telegram
ImportError: No module named telegram

**Comment by jaytee34** [comment]
@Skipper1990 das liest sich für mich, als hättest du die bisherige install.sh verwendet und nicht die für bullseye adaptiert. Magst du das bitte nochmals prüfen? @Schrolli91 hat das Script in install_bullseye.sh umbenannt.

**Comment by Skipper1990** [comment]
Nein, habe die Bullseye.sh genommen.

**Comment by Skipper1990** [comment]
Nein, habe die bullseye.sh genommen. Sonst hätte auch die Installation nicht geklappt 

Von meinem iPhone gesendet

**Comment by Skipper1990** [comment]
System nochmal neu aufgesetzt und alles installiert (auch mit der bullseye.sh) und der Fehler kommt weiterhin.

bei der Installation kam auch keine Fehlermeldung
Hier mal der Log von der Installation. Vielleicht findet jemanden einen fehler.

[setup_log.txt](https://github.com/Schrolli91/BOSWatch/files/8791562/setup_log.txt)
.

**Comment by Schrolli91** [comment]
@jaytee34 Hast du eine Idee zu dem Problem von @Skipper1990 ?

**Comment by Skipper1990** [comment]
Irgendwie wird Telegram nicht sauber installiert.

Bei sudo pip install telegram-bot kommt ein fehler.

 Using cached telegram-bot-0.1.tar.gz (51 kB)
ERROR: Command errored out with exit status 1:
ERROR: Could not find a version that satisfies the requirement telegram-bot
ERROR: No matching distribution found for telegram-bot

Vllt hilft das jemanden

**Comment by Skipper1990** [comment]
Werde die Tage mal 
sudo apt install python3-python-telegram-bot probieren und hoffen das damit der Bot sauber installiert wird und Boswatch die alarme dann weiterleitet via Telegram.

Edit: Versuch ohne Erfolge. Fehler besteht weiterhin

**Comment by Skipper1990** [comment]
Keiner eine Idee ? Der Pluginloader lädt Telegram nicht. Bzw sagt das er kein Plugin namens Telegram findet
