### ISSUE TITLE
Bosmon Übertragung schlägt fehl, Filter funktionieren nicht

### ISSUE THREAD

**Issue by 1nt4x** [Schrolli91/BOSWatch#548]
- **BOSWatch Version + Branch** 
2.5.2 / master

- **genutzte Plugins** 
Bosmon

- **Fehlerbeschreibung**

Keine Telegramm-Übertragung zu Bosmon mehr möglich, ebenfalls funktionieren die Filter in allow_ric und deny_ric nicht.
Es wird trotzdem versucht die Telegramme zu übertragen, im Log erscheint die Meldung "RIC is not in the allowed list"
Aber natürlich "RIC in between filter range" (0000000 - 9999999)

- **Logfile (Auszug)**

Traceback (most recent call last):
  File "/opt/boswatch/plugins/BosMon/BosMon.py", line 63, in bosMonRequest
    httprequest.request("POST", "/telegramin/"+globalVars.config.get("BosMon", "bosmon_channel")+"/input.xml", params, headers)
  File "/usr/lib/python2.7/httplib.py", line 1058, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1098, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 831, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out

- **ggf. Config File (Auszug)**

**Comment by Schrolli91** [comment]
Da der Fehler im `connect()` passiert und durch einen `timeout` rausfliegt, gehe ich hier klar von einem Problem der Verbindung zur Bosmon Instanz aus und sehe mit dem aktuellen Log keinen Fehler in BOSWatch.

```
File "/usr/lib/python2.7/httplib.py", line 854, in send
self.connect()
File "/usr/lib/python2.7/httplib.py", line 831, in connect
self.timeout, self.source_address)
File "/usr/lib/python2.7/socket.py", line 575, in create_connection
raise err
timeout: timed out
```
