### ISSUE TITLE
Debian 11 Bullseye Telegram Fehler 

### ISSUE THREAD

**Issue by Skipper1990** [Schrolli91/BOSWatch#550]
OS Bullseye und Python 3.8.4

Installation lief sauber durch, nur beim starte kommt ein fehler.

Info: Telegram mit sudo pip install python-telegram-bot installiert

Folgender fehler beim start von Boswatch

28.05.2022 13:02:11 - pluginLoader [DEBUG ] load plugin: Telegram
28.05.2022 13:02:11 - pluginLoader [ERROR ] cannot load plugin: Telegram
28.05.2022 13:02:11 - pluginLoader [DEBUG ] cannot load plugin: Telegram
Traceback (most recent call last):
File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
return imp.load_module(plugin["name"], *plugin["info"])
File "/opt/boswatch/plugins/Telegram/Telegram.py", line 14, in 
import telegram
ImportError: No module named telegram
28.05.2022 13:02:11 - pluginLoader [ERROR ] error loading plugin: Telegram
28.05.2022 13:02:11 - pluginLoader [DEBUG ] error loading plugin: Telegram
Traceback (most recent call last):
File "/opt/boswatch/includes/pluginLoader.py", line 32, in loadPlugins
plugin = loadPlugin(i)
File "/opt/boswatch/includes/pluginLoader.py", line 106, in loadPlugin
return imp.load_module(plugin["name"], *plugin["info"])
File "/opt/boswatch/plugins/Telegram/Telegram.py", line 14, in 
import telegram
ImportError: No module named telegram

Auch Sudo apt-get python3-python-telegram-bot probiert.

Fehler beim Start von Boswatch kommt immer noch  

Selber Fehler wie bei #504 
Keine der Vorschläge haben da geholfen

**Comment by dennisN75** [comment]
Habe genau das gleiche Problem aktuell. Gab es da mal eine Lösung dafür?
